ci(monorepo): cache multiple tags

diff --git a/.github/workflows/ci-package-registry.yaml b/.github/workflows/ci-package-registry.yaml
--- a/.github/workflows/ci-package-registry.yaml
+++ b/.github/workflows/ci-package-registry.yaml
@@ -5,9 +5,6 @@ on:
   pull_request:
   workflow_dispatch:
 
-env:
-  CACHE_PREFIX: snicco_1
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -17,10 +14,18 @@ jobs:
         php: [ '8.1', '8.0', '7.4']
         wp: [ '6.0', '5.9', '5.8']
     env:
+      CACHE_PREFIX: snicco_1
       APP_IMAGE_NAME: ghcr.io/snicco/app-ci-php${{ matrix.php }}
       WP_IMAGE_NAME: ghcr.io/snicco/wp-ci-php${{ matrix.php }}-wp${{ matrix.wp }}
       NGINX_IMAGE_NAME: ghcr.io/snicco/nginx-ci
       NODE_IMAGE_NAME: ghcr.io/snicco/node-ci
+      ENV: ci
+      APP_USER_NAME: runner
+      APP_USER_ID: 1001
+      APP_GROUP_NAME: docker
+      APP_GROUP_ID: 121
+      PHP_VERSION: ${{ matrix.php }}
+      WP_VERSION: ${{ matrix.wp }}
 
     steps:
       - uses: actions/checkout@v3
@@ -60,18 +65,10 @@ jobs:
           make docker-pull || true
           make docker-up
           make update
-        env:
-          ENV: ci
-          APP_USER_NAME: runner
-          APP_USER_ID: 1001
-          APP_GROUP_NAME: docker
-          APP_GROUP_ID: 121
-          PHP_VERSION: ${{ matrix.php }}
-          WP_VERSION: ${{ matrix.wp }}
 
       - name: 'Tests, PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
         run: |
-          make integration-tests ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+          make unit-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
 
       - name: EVALUATE
         run: |
@@ -79,7 +76,7 @@ jobs:
 
       - name: 'Push docker images'
         run: |
-          docker push ghcr.io/snicco/wp-ci-php${{ matrix.php }}-wp${{ matrix.wp }}
-          docker push ghcr.io/snicco/app-ci-php${{ matrix.php }}
-          docker push ghcr.io/snicco/node-ci
-          docker push ghcr.io/snicco/nginx-ci
+          docker push ${{ env.APP_IMAGE_NAME }}
+          docker push ${{ env.WP_IMAGE_NAME }}
+          docker push ${{ env.NODE_IMAGE_NAME }}
+          docker push ${{ env.NGINX_IMAGE_NAME }}
