ci(monorepo): pulling images separately

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -57,16 +57,23 @@ jobs:
       - name: 'Docker setup: ${{ matrix.php }}, WP ${{ matrix.wp }}'
         run: |
           make init
-          make docker-pull || true
-          make docker-up
+          make docker-pull SERVICE="db app wp" || true
+          make docker-up SERVICE="db app wp"
 
-#      - name: Setup tmate session
-#        uses: mxschmitt/action-tmate@v3
-
-      - name: 'Tests: PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
+      - name: 'Fast tests: PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
         run: |
           make build-codeception
           make unit-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+          make wpunit-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+          make usecase-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+          make integration-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+
+      - name: 'Slow tests tests: PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
+        run: |
+          make docker-pull SERVICE="nginx node chrome"
+          make docker-up SERVICE="nginx node chrome"
+          make cli-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+          make browser-tests || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
 
       - name: EVALUATE
         run: |
