ci(monorepo): quoted

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -134,6 +134,7 @@ jobs:
           echo $PACKAGES
           echo "::set-output name=matrix::$PACKAGES"
 
+
   Build-in-matrix:
     runs-on: ubuntu-latest
     needs: provide_packages
@@ -172,15 +173,15 @@ jobs:
 
       - name: 'Pull docker images'
         run: |
-          make docker-pull SERVICE=${{ matrix.packages.docker_services }} || true # This can fail if the tag does not exist yet.
+          make docker-pull SERVICE="${{ matrix.packages.docker_services }}" || true # This can fail if the tag does not exist yet.
 
       - name: 'Build docker images'
         run: |
-          make docker-build SERVICE=${{ matrix.packages.docker_services }}
+          make docker-build SERVICE="${{ matrix.packages.docker_services }}"
 
       - name: 'Parallel docker tests'
         run: |
-          make test-parallel-docker PACKAGES=${{ matrix.packages.rel_path }} SERVICE=${{ matrix.packages.docker_services }} QUIET=1 DOCKER_UP_ARGS=--detach
+          make test-parallel-docker PACKAGES=${{ matrix.packages.rel_path }} SERVICE="${{ matrix.packages.docker_services }}" QUIET=1 DOCKER_UP_ARGS=--detach
 
 
 
