ci(monorepo): with qa

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -59,9 +59,18 @@ jobs:
           make docker-build ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wp }}
           make docker-up ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 MODE=--detach PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wp }}
 
+      - name: 'QA'
+        if: matrix.php == '7.4' && matrix.wp == '6.0' # We only need to run QA once.
+        run:
+          make qa || echo "FAILED=QA" >> $GITHUB_ENV
+
       - name: 'Tests, PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
         run: |
-          make unit-tests ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121
+          make unit-tests ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 || echo "FAILED=Tests $FAILED" >> $GITHUB_ENV
+
+      - name: EVALUATE
+        run: |
+          if [ ! -z "$FAILED" ]; then echo "Failed at step $FAILED" && exit 1; fi
 
       - name: 'Save docker images'
         run: |
